:PROPERTIES:
:ID:       c7c7ccae-b4d0-4cb8-aee2-3aae2490c729
:END:
#+title: 分类
#+startup: overview
#+filetags: :MachineLearning:Model:分类:

* 阈值和混淆矩阵
** 阈值
假设现在有一个垃圾邮件检测的逻辑回归模型，该模型预测一个介于0~1之间的值，表示该电子邮件是垃圾邮件的概率。预测值为0.5表示该电子邮件是垃圾邮件的概率是50%，预测值为0.75表示该电子邮件是垃圾邮件的概率是75%，以此类推

然后需要将垃圾邮件顾虑到单独的邮件文件夹中。为此需要转换模型的原始数值输出，分为“垃圾邮件”和“非垃圾邮件”两类

那么需要选择一个阈值概率，称为 =分类阈值= 。然后，概率高于阈值的示例会被分配到正类别(要测试的类)，低于阈值的会被分配到负类别

假设模型为某封电子邮件评分为 0.99，预测该电子邮件是垃圾邮件的概率为 99%；为另一封电子邮件评分为 0.51，预测该电子邮件是垃圾邮件的概率为 51%。如果您将分类阈值设置为 0.5，模型将将这两封电子邮件都归类为垃圾邮件。如果您将阈值设置为 0.95，则只有得分为 0.99 的电子邮件才会被归类为垃圾邮件。

虽然 0.5 可能看起来是一个直观的阈值，但如果一种错误分类的代价大于另一种，或者类不平衡，则不建议使用该阈值。如果只有 0.01% 的电子邮件是垃圾邮件，或者将合法电子邮件归错会比让垃圾邮件进入收件箱更糟糕，那么如果将模型认为至少有 50% 的可能性是垃圾邮件的任何内容都标记为垃圾邮件，就会产生不理想的结果。

** 混淆矩阵
概率得分不是现实情况，也不是标准答案。二元分类器的每个输出有四种可能结果。在垃圾邮件分类器示例中，如果您将标准答案作为列，将模型的预测作为行，则会得到以下表格（称为混淆矩阵）：

|             | 实际正例                                                                                                 | 实际负例                                                                                           |
|-------------+-----------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------|
| 预测为正例 | 真正例 (TP)：垃圾邮件被正确分类为垃圾邮件。这些是系统自动发送到“垃圾邮件”文件夹的垃圾邮件。       | 假正例 (FP)：非垃圾邮件被误分类为垃圾邮件。这些是最终被移至“垃圾邮件”文件夹的正常电子邮件。 |
| 预测为负   | 假负例 (FN)：垃圾邮件被误分类为非垃圾邮件。这些垃圾邮件未被垃圾邮件过滤器捕获，而是进入了收件箱。 | 真负例 (TN)：非垃圾邮件被正确分类为非垃圾邮件。 这些是直接发送到收件箱的真实电子邮件。       |

请注意，每行的总和表示所有预测正例 (TP + FP) 和所有预测负例 (FN + TN)，无论其有效性如何。与此同时，每个列中的总和会显示所有真实正例 (TP + FN) 和所有真实负例 (FP + TN)，而不会考虑模型分类。

如果实际正例的总数与实际负例的总数不接近，则表示数据集不平衡。不平衡数据集的一个示例可能是一组数以千计的云彩照片，其中您感兴趣的罕见云彩类型（例如卷云）只出现了几次。

* 阈值对真正例、假正例和假负例的影响
一般来说，如果提高分类阈值，真正例和假正例都会减少，真负例和假负例都会增加。
* [[id:998b55d6-636d-4ac9-a5bb-b800ce0dd2f6][分类相关指标]]
* [[id:e02fc899-f694-4ec3-99f2-36710dca39cc][接收器操作特征曲线(ROC)]]
* [[id:2ea241f5-7b3e-4583-b9de-847fc8ad4cb0][预测偏差]]
* [[file:~/code/python/ML/google_tutorial/binary_classification_rice.py][编程作业]] 
