:PROPERTIES:
:ID:       69387d42-c46e-4b17-808c-f20a558f8291
:END:
#+title: python-DataStructure
#+startup: overview
#+filetags: :python:DataStructure:

* 列表
** 定义
#+begin_src plaintext
列表序列名称 = [列表中的元素1, 列表中的元素2, 列表中的元素3, ...]

注意: 列表是可变的
#+end_src
#+begin_src python :results output
fruit_list = ['orange', 'grape', 'mango']
# list列表类型支持直接打印
print(fruit_list)
# 打印列表的数据类型
print(type(fruit_list))  # <class 'list'>
#+end_src

#+RESULTS:
: ['orange', 'grape', 'mango']
: <class 'list'>

** 相关操作
*** 查
| 函数    | 作用                                                          |
|---------+---------------------------------------------------------------|
| index() | 指定数据所在位置的下标                                        |
| count() | 统计指定数据在当前列表中出现的次数                            |
| in      | 判断指定数据在某个列表序列，如果在返回True，否则返回False     |
| not in  | 判断指定数据不在某个列表序列，如果不在返回True，否则返回False |
*** 增
| 函数     | 作用                                                                   |
|----------+------------------------------------------------------------------------|
| append() | 增加指定数据到列表中                                                   |
| extend() | 列表结尾追加数据，如果数据是一个序列，则将这个序列的数据逐一添加到列表 |
| insert() | 指定位置新增数据                                                       |
*** 删
| 函数           | 作用                                             |
|----------------+--------------------------------------------------|
| del 列表[索引] | 删除列表中的某个元素                             |
| pop()          | 删除指定下标的数据(默认为最后一个)，并返回该数据 |
| remove()       | 移除列表中某个数据的第一个匹配项。               |
*** 修改
| 函数                    | 作用                   |
|-------------------------+------------------------|
| 列表[索引] = 修改后的值 | 修改列表中的某个元素   |
| reverse()               | 将数据序列进行倒叙排列 |
| sort()                  | 对列表序列进行排序     |
** 具体例子
#+begin_src python :results output
name_list = ['hello', 'apple', 'bike', 'back', 'bike']
# index
index = name_list.index('apple')
print(index)
# count
count = name_list.count('bike')
print(count)
# in and not in
print('apple' in name_list)
print('hack' not in name_list)
# append
if 'hack' not in name_list:
    name_list.append('hack')
print(name_list)
# extend
name_list2 = ['fruit', 'hike']
name_list.extend(name_list2)
print(name_list)
# insert
name_list.insert(0, 'xiaoming')
print(name_list)
# del
del name_list[1]
print(name_list)
# pop
pop_name = name_list.pop()
print(pop_name)
print(name_list)
# remove
name_list.remove('apple')
print(name_list)
# []
name_list[0] = 'xiaohong'
print(name_list)
# reverse
name_list.reverse()
print(name_list)
# sort
# NOTE: reverse=True(倒序) False(默认,正序)
name_list.sort(reverse=True)
print(name_list)
name_list.sort()
print(name_list)
#+end_src

#+RESULTS:
#+begin_example
1
2
True
True
['hello', 'apple', 'bike', 'back', 'bike', 'hack']
['hello', 'apple', 'bike', 'back', 'bike', 'hack', 'fruit', 'hike']
['xiaoming', 'hello', 'apple', 'bike', 'back', 'bike', 'hack', 'fruit', 'hike']
['xiaoming', 'apple', 'bike', 'back', 'bike', 'hack', 'fruit', 'hike']
hike
['xiaoming', 'apple', 'bike', 'back', 'bike', 'hack', 'fruit']
['xiaoming', 'bike', 'back', 'bike', 'hack', 'fruit']
['xiaohong', 'bike', 'back', 'bike', 'hack', 'fruit']
['fruit', 'hack', 'bike', 'back', 'bike', 'xiaohong']
['xiaohong', 'hack', 'fruit', 'bike', 'bike', 'back']
['back', 'bike', 'bike', 'fruit', 'hack', 'xiaohong']
#+end_example

** 列表遍历
#+begin_src python :results output
# while
star_list = ['西施', '王昭君', '杨玉环']
i = 0
while i < len(star_list):
    print(star_list[i])
    i += 1
print(100 * '#')
# for
for star in star_list:
    print(star)
#+end_src

#+RESULTS:
: 西施
: 王昭君
: 杨玉环
: ####################################################################################################
: 西施
: 王昭君
: 杨玉环
** 列表嵌套
#+begin_src python :results output
# 演示 列表嵌套
# 说明: 容器内部嵌套容器方式
# 需求: 有 三个班级, 分别为 前端1班 前端2班  后端1班, 每个班级分别有5位学生
# 定义 班级列表
front1_class = ['小明','小红','小刚','小丽','小强']
front2_class = ['小芳','小亮','小宇','小浩','小琪']
back1_class = ['小诺','小泽','小琳','小航','小彤']

# 定义 学校列表, 学校列表中有三个班级
school_list = [front1_class,front2_class,back1_class]

# 以上内容 如果直接使用列表嵌套写法
school_list = [
    ['小明','小红','小刚','小丽','小强'],
    ['小芳','小亮','小宇','小浩','小琪'],
    ['小诺','小泽','小琳','小航','小彤']
]

# 如何 获取里面的数据呢?  比如 我想获取到 小浩
front2_class = school_list[1]
name = front2_class[3]
print(name)

# 可以简写
name = school_list[1][3]
print(name)

# 如何遍历打印每一个元素
for classes in school_list:
    for name in classes:
        print(name)
    print("-----------")
#+end_src

#+RESULTS:
#+begin_example
小浩
小浩
小明
小红
小刚
小丽
小强
-----------
小芳
小亮
小宇
小浩
小琪
-----------
小诺
小泽
小琳
小航
小彤
-----------
#+end_example

* 元组
** 定义
定义元组使用小括号，且使用逗号隔开各个数据，数据可以是不同的数据类型。元组可以存储多个数据且数据不允许更改。
#+begin_src python
# 多个数据元组
tuple1 = (20, 30, 40)

# 单个数据元组
# NOTE: 如果定义的元组只有一个数据，那么这个数据后面也要添加逗号，否则数据类型为唯一的这个数据的数据类型。
tuple2 = (20,)
#+end_src
** 操作方法
| 函数       | 作用                                                                                  |
|------------+---------------------------------------------------------------------------------------|
| 元组[索引] | 根据索引下标查找元素                                                                  |
| index()    | 查找某个数据，如果数据存在返回对应的下标，否则报错，语法和列表、字符串的index方法相同 |
| count()    | 统计某个数据在当前元组出现的次数                                                      |
| len()      | 统计元组中数据的个数                                                                  |
** 示例
#+begin_src python :results output
tuple1 = (1, 1.2, "hello", ['apple', 'pie'])

print(tuple1)

for elm in tuple1:
    print(elm)
print(tuple1[0])
print(tuple1[1])
    
print(tuple1.index('hello'))
print(len(tuple1))
print(tuple1.count(tuple1[0]))
#+end_src
* 集合
** 定义
#+begin_src python :results output
# 1- 如何定义集合
# 格式:
#       格式一:  变量名称 = {元素1,元素2,元素3......}
#       格式二:  变量名称 = set()   空集合
# 特性: 无序 + 去重
# 定义一个有内容的集合
name_set = {'小明','小红','小刚','小明','小刚','小丽'}

print(name_set) #  去重 和 无序  发现每次都是不一样的 所以是无序的
print(type(name_set))
# 定义 空集合
# set2 = {}  # 此种定义方法 并不是定义空集合, 而是空的字典
empty_set = set()
print(type(empty_set))

# 获取数据: 遍历的方式
# for 循环
for name in name_set:
    print(name)
#+end_src

#+RESULTS:
: {'小明', '小红', '小刚', '小丽'}
: <class 'set'>
: <class 'set'>
: 小明
: 小红
: 小刚
: 小丽

** 相关操作
*** 查
#+begin_src python :results output
name_set = {'小明','小红','小刚'}
name_set.add('小强')
print(name_set)
#+end_src

#+RESULTS:
: {'小强', '小明', '小刚', '小红'}

*** 删
#+begin_src python :results output
name_set = {'小明','小红','小刚'}
name_set.remove('小红')
print(name_set)
#+end_src

#+RESULTS:
: {'小明', '小刚'}

*** 增
#+begin_src python :results output
name_set = {'小明','小红','小刚'}
print('小明' in name_set)  # True
print('小丽' not in name_set)  # True
#+end_src
** 示例
#+begin_src python :results output
num_set = {3, 4, 'xiaoming', False, True}
num_set.add('hello')
print(num_set)
num_set.remove('xiaoming')
print(num_set)
if 'xiaoming' not in num_set:
    num_set.add('xiaoming')

# NOTE: 集合自己会去重
num_set.add(10)
num_set.add(10)
num_set.add(10)
num_set.add(10)
num_set.add(10)
num_set.add(10)
num_set.add(10)
num_set.add(10)
num_set.add(10)
num_set.add(10)
num_set.add(10)
print(num_set)
#+end_src

#+RESULTS:
: {False, True, 3, 4, 'xiaoming', 'hello'}
: {False, True, 3, 4, 'hello'}
: {False, True, 3, 4, 'xiaoming', 'hello', 10}

* 字典
** 定义
#+begin_src python :results output
# 1- 演示: 如何定义字典
# 格式:
#   格式1:  变量名称 = {key1:value1,key2:value2,key3:value3.....}
#   格式2:  变量名称 = {}  或者 变量名称 = dict()   空字典

# 构建一个有内容的字典
person = {'name': '小明', 'age': 19, 'address': "上海市浦东新区张江镇", 'sex': '男', 'hobby': '篮球、足球、游泳'}
print(person)
print(type(person))

# 构建空字典
dict1 = {}
dict2 = dict()
print(dict1)
print(type(dict1))
print(dict2)
print(type(dict2))

# 遍历操作
for key in person:
    print(key)
    print(person[key])
#+end_src

#+RESULTS:
#+begin_example
{'name': '小明', 'age': 19, 'address': '上海市浦东新区张江镇', 'sex': '男', 'hobby': '篮球、足球、游泳'}
<class 'dict'>
{}
<class 'dict'>
{}
<class 'dict'>
name
小明
age
19
address
上海市浦东新区张江镇
sex
男
hobby
篮球、足球、游泳
#+end_example

** 操作
*** 增
#+begin_src 
字典名称[key] = value
注：如果key存在则修改这个key对应的值；如果key不存在则新增此键值对。
#+end_src
*** 删
#+begin_src python :results output
person = {'name': '小明', 'age': 19}
del person['age']
print(person)
#+end_src

#+RESULTS:
: {'name': '小明'}

#+begin_src python :resuts output
person = {'name': '小明', 'age': 19}
person.clear()
print(person)
#+end_src

#+RESULTS:
: None

*** 改
#+begin_src 
字典名称[key] = value
注：如果key存在则修改这个key对应的值；如果key不存在则新增此键值对。
#+end_src
#+begin_src python :results output
person = {'name': '小明', 'age': 19, 'address': '上海市浦东新区'}
person['address'] = '上海市黄浦区'
print(person)
#+end_src

*** 查
| 函数     | 作用                                |
|----------+-------------------------------------|
| keys()   | 以列表返回一个字典所有的键          |
| values() | 以列表返回字典中的所有值            |
| items()  | 以列表返回可遍历的(键, 值) 元组数据 |
**** 提取所有key
#+begin_src python :results output
person = {'name': '小明', 'age': 19, 'address': '上海市浦东新区'}
print(person.keys())
#+end_src
**** 提取所有value
#+begin_src python :results output
person = {'name': '小明', 'age': 19, 'address': '上海市浦东新区'}
print(person.values())
#+end_src
**** items方法
#+begin_src python :results output
person = {'name': '小明', 'age': 19, 'address': '上海市浦东新区'}
print(person.items())
#+end_src
** 示例
#+begin_src python :results output
person = {
    'name': 'Encounter',
    'age': '19',
    'address': 'China',
    'sex': 'male',
    'hobby': 'coding'
}

print(person)
person["birthday"] = '2005-8-20'
print(person)
person['sex'] = 'female'
print(person)

print(person['address'])

keys_list = person.keys()
print(keys_list)
value_list = person.values()
print(value_list)

items = person.items()
print(items)
for item in items:
    print(item)
    print(f'{item[0]}, {item[1]}')
#+end_src

* 字符串
** 字符串格式化
#+begin_src python :results output
print ( "My name is %s and weight is %d kg!" % ('Zara', 21) ) 
#+end_src

#+RESULTS:
: My name is Zara and weight is 21 kg!
** 三引号
#+begin_src python :results output
 errHTML = '''
<HTML><HEAD><TITLE>
Friends CGI Demo</TITLE></HEAD>
<BODY><H3>ERROR</H3>
<B>%s</B><P>
<FORM><INPUT TYPE=button VALUE=Back
ONCLICK="window.history.back()"></FORM>
</BODY></HTML>
'''
#+end_src

** api
| 函数名                                              | 描述                                                                                                                    |
|-----------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------|
| string.capitalize()                                 | 把字符串的第一个字符大写                                                                                                |
| string.find(str, beg=0, end=len(string))            | 检测 str 是否包含在 string 中，如果 beg 和 end 指定范围，则检查是否包含在指定范围内，如果是返回开始的索引值，否则返回-1 |
| string.index(str, beg=0, end=len(string))           | 跟find()方法一样，只不过如果str不在 string中会报一个异常.                                                               |
| string.isalnum()                                    | 如果 string 至少有一个字符并且所有字符都是字母或数字则返回 True,否则返回 False                                          |
| string.isalpha()                                    | 如果 string 至少有一个字符并且所有字符都是字母则返回 True,否则返回 False                                                |
| string.join(seq)                                    | 以 string 作为分隔符，将 seq 中所有的元素(的字符串表示)合并为一个新的字符串                                             |
| string.lower()                                      | 转换 string 中所有大写字符为小写.                                                                                       |
| string.replace(str1, str2,  num=string.count(str1)) | 把 string 中的 str1 替换成 str2,如果 num 指定，则替换不超过 num 次                                                      |
| string.split(str="", num=string.count(str))         | 以 str 为分隔符切片 string，如果 num 有指定值，则仅分隔 num+1 个子字符串                                                |
| string.upper()                                      | 转换 string 中的小写字母为大写                                                                                          |
