:PROPERTIES:
:ID:       67304125-79ef-4135-abc3-e6c55058bc0e
:END:
#+title: python-IO
#+startup: overview
#+filetags: :python:IO:

* 输入输出
** 格式化输出
*** f-string
#+begin_src python :results output
name = "李四"
age = 20
score = 95.5
# 基础用法
print(f"姓名：{name}，年龄：{age}，成绩：{score}")
# 格式控制（保留2位小数）
print(f"成绩：{score:.2f}")
# 数字补零（6位宽度）
print(f"学号：{1:06d}")  # 输出：000001
#+end_src
*** format()
#+begin_src python :results output
print("姓名：{}，年龄：{}".format(name, age))
# 指定位置
print("年龄：{1}，姓名：{0}".format(name, age))
# 格式控制
print("成绩：{:.2f}".format(score))
#+end_src
*** 占位符
#+begin_src python :results output
print("姓名：%s，年龄：%d，成绩：%.2f" % (name, age, score))
#+end_src
** 转义字符
| 转义符 | 功能               |
|--------+--------------------|
| \n     | 换行               |
| \t     | 制表符（4 个空格） |
| \      | 反斜杠本身         |
| "      | 双引号             |
| '      | 单引号             |

示例
#+begin_src python :results output
print("姓名：{}\t年龄：{}\n成绩：{:.2f}".format(name, age, score))
# 自定义print结束符（默认\n）
print("Hello", end=" ")
print("Python")  # 输出：Hello Python
#+end_src

** 输入函数 input()
#+begin_src python :results output
# NOTE: 所有输入均是字符串
# 基础用法
name = input("请输入您的姓名：")
age = input("请输入您的年龄：")
print(f"您输入的姓名：{name}，年龄：{age}")

# 带提示的输入
phone = input("请输入您的手机号：")
print(f"手机号：{phone}，类型：{type(phone)}")
#+end_src
* 文件基本操作
** open()
#+begin_src
file object = open(file_name [, access_mode][, buffering])
#+end_src
+ file_name
   file_name变量是一个包含了你要访问的文件名称的字符串值。
+ access_mode
  access_mode决定了打开文件的模式：只读，写入，追加等。所有可取值见如下的完全列表。这个参数是非强制的，默认文件访问模式为只读(r)。
+ buffering
  如果buffering的值被设为0，就不会有寄存。如果buffering的值取1，访问文件时会寄存行。如果将buffering的值设为大于1的整数，表明了这就是的寄存区的缓冲大小。如果取负值，寄存区的缓冲大小则为系统默认。
  
关于文件打开模式如下：
| 模式 | 描述                                                                                                                                                               |
|------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| t    | 文本模式 (默认)。                                                                                                                                                  |
| x    | 写模式，新建一个文件，如果该文件已存在则会报错。                                                                                                                   |
| b    | 二进制模式。                                                                                                                                                       |
| +    | 打开一个文件进行更新(可读可写)。                                                                                                                                   |
| r    | 以只读方式打开文件。文件的指针将会放在文件的开头。这是默认模式。                                                                                                   |
| w    | 打开一个文件只用于写入。如果该文件已存在则打开文件，并从开头开始编辑，即原有内容会被删除。如果该文件不存在，创建新文件。                                           |
| r+   | 打开一个文件用于读写。文件指针将会放在文件的开头。                                                                                                                 |
| rb+  | 以二进制格式打开一个文件用于读写。文件指针将会放在文件的开头。一般用于非文本文件如图片等。                                                                         |
| w+   | 打开一个文件用于读写。如果该文件已存在则打开文件，并从开头开始编辑，即原有内容会被删除。如果该文件不存在，创建新文件。                                             |
| a    | 打开一个文件用于追加。如果该文件已存在，文件指针将会放在文件的结尾。也就是说，新的内容将会被写入到已有内容之后。如果该文件不存在，创建新文件进行写入。             |
| ab   | 以二进制格式打开一个文件用于追加。如果该文件已存在，文件指针将会放在文件的结尾。也就是说，新的内容将会被写入到已有内容之后。如果该文件不存在，创建新文件进行写入。 |
| a+   | 打开一个文件用于读写。如果该文件已存在，文件指针将会放在文件的结尾。文件打开时会是追加模式。如果该文件不存在，创建新文件用于读写。                                 |
| ab+  | 以二进制格式打开一个文件用于追加。如果该文件已存在，文件指针将会放在文件的结尾。如果该文件不存在，创建新文件用于读写。                                             |

*** 示例
#+begin_src python :results output
# 假设我们要向 log.txt 追加一行内容
file_path = "logs/log.txt"
new_content = "这是要追加的新信息。\n"

# 'a' 代表 append（追加）模式
# encoding='utf-8' 是工程实践中避免乱码的必备习惯
with open(file_path, mode='a', encoding='utf-8') as f:
    f.write(new_content)
#+end_src
如果路径比较复杂，可以使用pathlib
#+begin_src python :results output
from pathlib import Path
file_path = Path("logs") / "log.txt"
# 确保父目录存在
file_path.parent.mkdir(parents=True, exist_ok=True)
with file_path.open(mode='a', encoding='utf-8') as f:
    f.write("工程化的追加写入方式\n")
#+end_src
** close()
 File 对象的 close（）方法刷新缓冲区里任何还没写入的信息，并关闭该文件，这之后便不能再进行写入。当一个文件对象的引用被重新指定给另一个文件时，Python 会关闭之前的文件。用 close（）方法关闭文件是一个很好的习惯。 

#+begin_src
fileObject.close()
#+end_src
** read()
read（）方法从一个打开的文件中读取一个字符串。需要重点注意的是，Python字符串可以是二进制数据，而不是仅仅是文字。
#+begin_src
fileObject.read([count])
#+end_src
在这里，被传递的参数是要从已打开文件中读取的字节计数。该方法从文件的开头开始读入，如果没有传入count，它会尝试尽可能多地读取更多的内容，很可能是直到文件的末尾。 

** write()
 write()方法可将任何字符串写入一个打开的文件。需要重点注意的是，Python字符串可以是二进制数据，而不是仅仅是文字。write()方法不会在字符串的结尾添加换行符('\n')： 
#+begin_src 
fileObject.write(string)
#+end_src

** 例子
#+begin_src python :results output
from pathlib import Path

file_path = Path("logs") / "app.log"
file_path.parent.mkdir(parents=True, exist_ok=True)

with file_path.open(mode='a', encoding='utf-8') as f:
    f.write("hello world\n")
    f.close()

with file_path.open(mode='r', encoding='utf-8') as f:
    str = f.read()
    print(str)
    f.close()
#+end_src
* 文件定位
=tell()= 可以当前文件内读取的位置， =seek(offset, [, from])= 可以改变读取文件内的位置，offset标识移动的字节数，from表示开始移动字节的参考位置
#+begin_src python :results output
from pathlib import Path

file_path = Path("logs") / "app.log"
file_path.parent.mkdir(parents=True, exist_ok=True)

with file_path.open(mode='r', encoding='utf-8') as f:
    str = f.read(11)
    print(f'{str}\ncurrent position: {f.tell()}')
    position = f.seek(0, 0)
    str = f.read(11)
    print(f'reread str: {str}')
    f.close()
#+end_src
* 重命名文件
#+begin_src
os.rename(current_file_name, new_file_name)
#+end_src
* 删除文件
#+begin_src 
os.remove(file_name)
#+end_src
* 目录操作
+ mkdir()
  #+begin_src
  os.mkdir(dirname)
  #+end_src
+ chdir()
  #+begin_src
  os.chdir(dirname)
  #+end_src
+ getcwd()
  #+begin_src
  print( os.getcwd() )
  #+end_src
+ rmdir()
  #+begin_src
  os.rmdir(dirname) 
  #+end_src
  
** 示例
#+begin_src python :results output
import os
os.makedirs("tmp", exist_ok=True) # 如果目录不存在，创建目录
# os.mkdir("tmp")
os.chdir("tmp")
print(os.getcwd())
os.chdir("..")
print(os.getcwd())
os.rmdir("tmp")
#+end_src

